// Flip the scroll y axis
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
#define CHARYBDIS_CARRET_REVERSE_Y

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 750
#define CHARYBDIS_MINIMUM_SNIPING_DPI 200

#define CHARYBDIS_DRAGSCROLL_DPI 200

#define CUSTOM_FN_RIGHT KC_BRIGHTNESS_UP
#define CUSTOM_FN_LEFT KC_BRIGHTNESS_DOWN
#define CUSTOM_FN_UP KC_AUDIO_VOL_UP
#define CUSTOM_FN_DOWN KC_AUDIO_VOL_DOWN

